export default {
  DELETE_CONTACT: "DELETE_CONTACT",
  UPDATE_FILTER: "UPDATE_FILTER",
  CHANGE_INPUT_NAME: "CHANGE_INPUT_NAME",
  CHANGE_INPUT_NUMBER: "CHANGE_INPUT_NUMBER",
  HANDLE_SUBMIT: " HANDLE_SUBMIT",
  CHANGE_INPUT_FILTER: "CHANGE_INPUT_FILTER",
  SHOW_NOTIFICATION: "SHOW_NOTIFICATION"
};
